[package]
name = "post-benchmarks"
version = "0.1.0"
edition = "2021"

[dependencies]
aes = "0.8.2"
blake3 = "1.3.3"
itertools = "0.10.5"
siphasher = "0.3.10"

[dev-dependencies]
criterion = "0.4.0"

[[bench]]
name = "bench_algos"
harness = false


[profile.release]
debug = true
